#!/usr/bin/env node
/**
 * Builds prisma/schema.prisma for Jumaah Cloud: the Community core schema plus prisma/cloud.prisma.
 * The core schema path defaults to the Community checkout next to this repository (see CORE_SCHEMA).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const candidates = [
  process.env.CORE_SCHEMA,
  resolve(here, '../../../packages/db/prisma/schema.prisma'), // inside the Jumaah monorepo (cloud/db)
  resolve(here, '../../../community/packages/db/prisma/schema.prisma'), // jumaah-site: community submodule
].filter(Boolean);
const corePath = candidates.find((p) => existsSync(p));
if (!corePath) throw new Error('core schema not found; set CORE_SCHEMA');

let core = readFileSync(corePath, 'utf8');
const cloud = readFileSync(resolve(here, '../prisma/cloud.prisma'), 'utf8');

// Own client output so the cloud client never overwrites the core one in node_modules.
core = core.replace(/generator client \{[\s\S]*?\n\}/, 'generator client {\n  provider        = "prisma-client-js"\n  output          = "../generated/client"\n  previewFeatures = ["relationJoins"]\n}');

const extendRe = /\/\/ @extend (\w+)\n([\s\S]*?)\/\/ @end\n/g;
let rest = cloud;
let m;
while ((m = extendRe.exec(cloud))) {
  const [whole, model, body] = m;
  const modelRe = new RegExp('(model ' + model + ' \\{[\\s\\S]*?)(\\n\\}\\n)');
  if (!modelRe.test(core)) throw new Error('core model not found: ' + model);
  core = core.replace(modelRe, (_all, head, tail) => head + '\n' + body.replace(/\n+$/, '') + tail);
  rest = rest.replace(whole, '');
}
rest = rest.replace(/^\/\/[^\n]*\n(?:\/\/[^\n]*\n)*\n?/, ''); // header comment
const out = '// GENERATED by scripts/compose-schema.mjs from the Community core schema + prisma/cloud.prisma. Do not edit.\n\n' + core.trimEnd() + '\n\n' + rest.trim() + '\n';
writeFileSync(resolve(here, '../prisma/schema.prisma'), out);
console.log('cloud schema composed from', corePath);
