// Downloads the web fonts the site uses from Google Fonts once, so the site can serve them itself
// (no third-party request per visitor). Writes assets/fonts/*.woff2, src/assets/fonts.css and assets/fonts/manifest.json.
// Run again only when the font list changes:  node tools/fetch-fonts.mjs
// Licenses: all families are SIL OFL 1.1 (Bricolage Grotesque, Newsreader, IBM Plex Mono, Amiri, Noto families).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "assets", "fonts");
const FAMILIES = [
  "Bricolage+Grotesque:opsz,wght@12..96,700;12..96,800",
  "Newsreader:opsz,wght@6..72,400;6..72,500",
  "IBM+Plex+Mono:wght@400;500",
  "Amiri:wght@400;700",
  "Noto+Nastaliq+Urdu",
  "Noto+Sans+Bengali:wght@400;500",
  "Noto+Kufi+Arabic:wght@700;800",
  "Noto+Naskh+Arabic:wght@400;500",
];
const KEEP_SUBSETS = new Set(["latin", "latin-ext", "arabic", "bengali"]);
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"; // woff2 + unicode-range

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => "family=" + f).join("&")}&display=swap`;
const css = await (await fetch(url, { headers: { "user-agent": UA } })).text();

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const blocks = [...css.matchAll(/\/\* (\w[\w-]*) \*\/\s*@font-face \{([\s\S]*?)\}/g)];
const manifest = {};
let out = "/* Self-hosted web fonts. Generated by tools/fetch-fonts.mjs. All families are SIL OFL 1.1. */\n";
let n = 0;
for (const [, subset, body] of blocks) {
  if (!KEEP_SUBSETS.has(subset)) continue;
  const family = /font-family:\s*'([^']+)'/.exec(body)[1];
  const weight = (/font-weight:\s*([\d ]+)/.exec(body) || [, "400"])[1].trim().replace(/\s+/g, "-");
  const src = /url\((https:[^)]+\.woff2)\)/.exec(body)[1];
  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const file = `${slug}-${subset}-${weight}.woff2`;
  const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
  fs.writeFileSync(path.join(OUT, file), buf);
  n++;
  (manifest[family] ||= {})[`${subset}-${weight}`] = { file, bytes: buf.length };
  out += `/* ${subset} */\n@font-face {${body.replace(src, `/assets/fonts/${file}`).replace(/\n\s*/g, " ").trim()}}\n`;
}
fs.writeFileSync(path.join(ROOT, "src", "assets", "fonts.css"), out);
fs.writeFileSync(path.join(OUT, "manifest.json"), JSON.stringify(manifest, null, 2));
const total = Object.values(manifest).flatMap((m) => Object.values(m)).reduce((a, b) => a + b.bytes, 0);
console.log(`Saved ${n} font files (${(total / 1024).toFixed(0)} KB) and src/assets/fonts.css`);
