/**
 * Short on-screen phrases in every supported language (see packages/shared/src/languages.ts).
 * These are rendered inside each language panel, so they must exist for every code; English is the fallback.
 */
export type PhraseKey = 'imamSpeaking' | 'translationPending' | 'paused' | 'ended' | 'waiting';

export const PHRASES: Record<PhraseKey, Record<string, string>> = {
  imamSpeaking: {
    ar: 'الإمام يتحدث',
    en: 'The imam is speaking',
    ur: 'امام خطاب فرما رہے ہیں',
    bn: 'ইমাম বক্তব্য রাখছেন',
    tr: 'İmam konuşuyor',
    id: 'Imam sedang berbicara',
    ms: 'Imam sedang berucap',
    tl: 'Nagsasalita ang imam',
    am: 'ኢማሙ እየተናገሩ ነው',
    zh: '伊玛目正在讲话',
    fr: "L'imam parle",
    es: 'El imam está hablando',
    de: 'Der Imam spricht',
    ru: 'Имам говорит',
    hi: 'इमाम बोल रहे हैं',
    fa: 'امام در حال سخنرانی است',
    ps: 'امام خبرې کوي',
    so: 'Imaamku wuu hadlayaa',
    sw: 'Imamu anazungumza',
    ha: 'Limami yana magana',
    ta: 'இமாம் பேசிக்கொண்டிருக்கிறார்',
    ml: 'ഇമാം സംസാരിക്കുന്നു',
  },
  translationPending: {
    ar: 'قيد الترجمة',
    en: 'Translation pending',
    ur: 'ترجمہ زیرِ تکمیل ہے',
    bn: 'অনুবাদ প্রক্রিয়াধীন',
    tr: 'Çeviri bekleniyor',
    id: 'Terjemahan sedang diproses',
    ms: 'Terjemahan sedang diproses',
    tl: 'Hinihintay ang salin',
    am: 'ትርጉም በመጠባበቅ ላይ',
    zh: '翻译待完成',
    fr: 'Traduction en attente',
    es: 'Traducción pendiente',
    de: 'Übersetzung ausstehend',
    ru: 'Перевод готовится',
    hi: 'अनुवाद लंबित है',
    fa: 'ترجمه در حال آماده‌سازی است',
    ps: 'ژباړه روانه ده',
    so: 'Tarjumaddu waa socotaa',
    sw: 'Tafsiri inasubiri',
    ha: 'Fassara na jira',
    ta: 'மொழிபெயர்ப்பு நிலுவையில் உள்ளது',
    ml: 'വിവർത്തനം തയ്യാറാകുന്നു',
  },
  paused: {
    ar: 'توقف مؤقت',
    en: 'Paused',
    ur: 'وقفہ',
    bn: 'বিরতি',
    tr: 'Duraklatıldı',
    id: 'Dijeda',
    ms: 'Dijeda',
    tl: 'Naka-pause',
    am: 'ለጊዜው ቆሟል',
    zh: '已暂停',
    fr: 'En pause',
    es: 'En pausa',
    de: 'Pausiert',
    ru: 'Пауза',
    hi: 'रुका हुआ है',
    fa: 'مکث',
    ps: 'ځنډول شوی',
    so: 'Waa la hakiyay',
    sw: 'Imesimamishwa kwa muda',
    ha: 'An dakata',
    ta: 'இடைநிறுத்தப்பட்டது',
    ml: 'താൽക്കാലികമായി നിർത്തി',
  },
  ended: {
    ar: 'انتهت الخطبة',
    en: 'The khutbah has ended',
    ur: 'خطبہ ختم ہو گیا',
    bn: 'খুতবা শেষ হয়েছে',
    tr: 'Hutbe sona erdi',
    id: 'Khutbah telah selesai',
    ms: 'Khutbah telah tamat',
    tl: 'Natapos na ang khutbah',
    am: 'ኹጥባው ተጠናቋል',
    zh: '讲道已结束',
    fr: 'La khutba est terminée',
    es: 'La jutba ha terminado',
    de: 'Die Chutba ist beendet',
    ru: 'Хутба завершена',
    hi: 'ख़ुत्बा समाप्त हुआ',
    fa: 'خطبه به پایان رسید',
    ps: 'خطبه پای ته ورسېده',
    so: 'Khudbaddu way dhammaatay',
    sw: 'Khutba imekamilika',
    ha: 'Huduba ta ƙare',
    ta: 'குத்பா முடிவடைந்தது',
    ml: 'ഖുതുബ അവസാനിച്ചു',
  },
  waiting: {
    ar: 'بانتظار بدء الخطبة',
    en: 'Waiting for the khutbah to begin',
    ur: 'خطبے کے آغاز کا انتظار ہے',
    bn: 'খুতবা শুরুর অপেক্ষায়',
    tr: 'Hutbenin başlaması bekleniyor',
    id: 'Menunggu khutbah dimulai',
    ms: 'Menunggu khutbah bermula',
    tl: 'Naghihintay na magsimula ang khutbah',
    am: 'ኹጥባው እስኪጀምር በመጠበቅ ላይ',
    zh: '等待讲道开始',
    fr: 'En attente du début de la khutba',
    es: 'Esperando el inicio de la jutba',
    de: 'Warten auf den Beginn der Chutba',
    ru: 'Ожидание начала хутбы',
    hi: 'ख़ुत्बा शुरू होने की प्रतीक्षा है',
    fa: 'در انتظار آغاز خطبه',
    ps: 'د خطبې د پیل انتظار',
    so: 'Waxaa la sugayaa bilowga khudbadda',
    sw: 'Inasubiri khutba ianze',
    ha: 'Ana jiran fara huduba',
    ta: 'குத்பா தொடங்க காத்திருக்கிறோம்',
    ml: 'ഖുതുബ ആരംഭിക്കാൻ കാത്തിരിക്കുന്നു',
  },
};

/** Phrase in `lang`, falling back to English. */
export function phrase(key: PhraseKey, lang: string): string {
  const table = PHRASES[key];
  return table[lang] ?? table[lang.split('-')[0]] ?? table.en;
}
